<?xml version="1.0"?>
<!-- CORBA XML document created by XMLSerializer 1.3 at 2015-01-21 13:07:04 UTC, from SL 2.55-r18120 built 2010-06-24 10:17:53 UTC -->
<!DOCTYPE any [
<!ELEMENT any (any|typecode|sequence|array|struct|union|exception|string|objectref|enum|boolean|char|octet|short|ushort|long|ulong|float|double)?>
<!ATTLIST any name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED version CDATA #IMPLIED>
<!ELEMENT typecode (any|typecode|sequence|array|struct|union|exception|string|objectref|enum|boolean|char|octet|short|ushort|long|ulong|float|double)?>
<!ATTLIST typecode name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT sequence ((any|typecode|sequence|array|struct|union|exception|string|objectref)+|(enum|boolean|char|octet|short|ushort|long|ulong|float|double))?>
<!ATTLIST sequence name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED length NMTOKEN #REQUIRED bound NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT array ((any|typecode|sequence|array|struct|union|exception|string|objectref)+|(enum|boolean|char|octet|short|ushort|long|ulong|float|double))?>
<!ATTLIST array name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED length NMTOKEN #REQUIRED label NMTOKEN #IMPLIED>
<!ELEMENT struct (any|typecode|sequence|array|struct|union|exception|string|objectref|enum|boolean|char|octet|short|ushort|long|ulong|float|double)*>
<!ATTLIST struct name NMTOKEN #IMPLIED type_id CDATA #REQUIRED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT union (any|typecode|sequence|array|struct|union|exception|string|objectref|enum|boolean|char|octet|short|ushort|long|ulong|float|double)*>
<!ATTLIST union name NMTOKEN #IMPLIED type_id CDATA #REQUIRED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT exception (any|typecode|sequence|array|struct|union|exception|string|objectref|enum|boolean|char|octet|short|ushort|long|ulong|float|double)*>
<!ATTLIST exception name NMTOKEN #IMPLIED type_id CDATA #REQUIRED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT string (#PCDATA)>
<!ATTLIST string name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED bound NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT objectref (#PCDATA)>
<!ATTLIST objectref name NMTOKEN #IMPLIED type_id CDATA #REQUIRED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT enum (#PCDATA)>
<!ATTLIST enum name NMTOKEN #IMPLIED type_id CDATA #REQUIRED type_name NMTOKEN #IMPLIED values NMTOKENS #REQUIRED label NMTOKEN #IMPLIED>
<!ELEMENT boolean (#PCDATA)>
<!ATTLIST boolean name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT char (#PCDATA)>
<!ATTLIST char name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT octet (#PCDATA)>
<!ATTLIST octet name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT short (#PCDATA)>
<!ATTLIST short name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT ushort (#PCDATA)>
<!ATTLIST ushort name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT long (#PCDATA)>
<!ATTLIST long name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT ulong (#PCDATA)>
<!ATTLIST ulong name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT float (#PCDATA)>
<!ATTLIST float name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT double (#PCDATA)>
<!ATTLIST double name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
]>
<any version="1.3">
<sequence length="1" type_id="IDL:specs.de/Serializer/RegionGroupSeq:1.0" type_name="RegionGroupSeq">
<struct type_id="IDL:specs.de/Serializer/RegionGroup:1.0" type_name="RegionGroup">
<string name="name">Group1</string>
<sequence name="regions" length="2" type_id="IDL:specs.de/Serializer/RegionDataSeq:1.0" type_name="RegionDataSeq">
<struct type_id="IDL:specs.de/Serializer/RegionData:1.0" type_name="RegionData">
<string name="name">1:3 Cu:Ru</string>
<struct name="region" type_id="IDL:specs.de/SurfaceAnalysis/RegionDef:1.0" type_name="RegionDef">
<string name="analysis_method">ISS</string>
<string name="analyzer_lens">HighMagnification</string>
<string name="analyzer_slit">4: 1dia\6x20</string>
<struct name="scan_mode" type_id="IDL:specs.de/SurfaceAnalysis/ScanMode:1.0" type_name="ScanMode">
<string name="name">FixedRetardingRatio</string>
<ulong name="flags" type_id="IDL:specs.de/SurfaceAnalysis/ScanModeFlags:1.0" type_name="ScanModeFlags">6</ulong>
</struct>
<ulong name="num_scans">1</ulong>
<ulong name="curves_per_scan">1</ulong>
<ulong name="values_per_curve">1094</ulong>
<double name="dwell_time">0.1</double>
<double name="scan_delta">1</double>
<double name="excitation_energy">0</double>
<double name="kinetic_energy">6.6</double>
<double name="pass_energy">0.3</double>
<double name="bias_voltage">2000</double>
<double name="detector_voltage">2600</double>
<double name="effective_workfunction">4.5</double>
</struct>
<ulong name="mcd_head">0</ulong>
<ulong name="mcd_tail">0</ulong>
<struct name="analyzer_info" type_id="IDL:specs.de/SurfaceAnalysis/AnalyzerInfo:1.0" type_name="AnalyzerInfo">
<string name="name">PHOIBOS HSA3000 SCD</string>
<sequence name="detectors" length="1" type_id="IDL:specs.de/SurfaceAnalysis/DetectorSeq:1.0" type_name="DetectorSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="shift">0</double>
<double name="gain">1</double>
<sequence name="parameters" length="2" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Threshold [mV]</string>
<any name="value">
<double>4.306640625</double>
</any>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Deadtime [ns]</string>
<any name="value">
<double>0</double>
</any>
</struct>
</sequence>
</struct>
</sequence>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name"/>
<any name="value"/>
</struct>
</sequence>
</struct>
<struct name="source_info" type_id="IDL:specs.de/SurfaceAnalysis/SourceInfo:1.0" type_name="SourceInfo">
<string name="name">IonGunDummy</string>
<sequence name="excitations" length="1" type_id="IDL:specs.de/SurfaceAnalysis/ExcitationSeq:1.0" type_name="ExcitationSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Excitation:1.0" type_name="Excitation">
<double name="energy">0</double>
<double name="lorentz_width">0</double>
<double name="gauss_width">0</double>
<double name="intensity">0</double>
</struct>
</sequence>
<sequence name="parameters" length="7" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Current [nA]</string>
<any name="value">
<double>0</double>
</any>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Energy [kV]</string>
<any name="value">
<double>1000</double>
</any>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Angle [deg]</string>
<any name="value">
<double>130</double>
</any>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Atomic number</string>
<any name="value">
<long>2</long>
</any>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Atomic weight</string>
<any name="value">
<double>4</double>
</any>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Number of atoms</string>
<any name="value">
<long>1</long>
</any>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Charge sign and number</string>
<any name="value">
<long>1</long>
</any>
</struct>
</sequence>
<boolean name="intensity_scaling">0</boolean>
</struct>
<struct name="remote_info" type_id="IDL:specs.de/SurfaceAnalysis/RemoteInfo:1.0" type_name="RemoteInfo">
<string name="name"/>
<enum name="frequency" values="Never PerRegion PerScan PerValue AfterRegion AfterScan AfterValue" type_id="IDL:specs.de/SurfaceAnalysis/RemoteFrequency:1.0" type_name="RemoteFrequency">Never</enum>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name"/>
<any name="value"/>
</struct>
</sequence>
<sequence name="channel_names" length="0" type_id="IDL:specs.de/SurfaceAnalysis/StringSeq:1.0" type_name="StringSeq">
<string/>
</sequence>
<sequence name="channel_units" length="0" type_id="IDL:specs.de/SurfaceAnalysis/StringSeq:1.0" type_name="StringSeq">
<string/>
</sequence>
</struct>
<sequence name="cycles" length="1" type_id="IDL:specs.de/Serializer/CycleSeq:1.0" type_name="CycleSeq">
<struct type_id="IDL:specs.de/Serializer/Cycle:1.0" type_name="Cycle">
<ulong name="time">1364217099</ulong>
<sequence name="scans" length="1" type_id="IDL:specs.de/Serializer/ScanSeq:1.0" type_name="ScanSeq">
<struct type_id="IDL:specs.de/Serializer/ScanData:1.0" type_name="ScanData">
<sequence name="counts" length="1094" type_id="IDL:specs.de/SurfaceAnalysis/CountsSeq:1.0" type_name="CountsSeq">
<ulong type_id="IDL:specs.de/SurfaceAnalysis/Counts:1.0" type_name="Counts">
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
260
244
81
52
29
39
64
57
66
85
73
68
76
60
89
68
68
66
74
75
52
66
48
55
55
44
35
52
44
29
42
36
40
23
37
36
27
25
26
36
19
30
18
25
29
17
16
10
11
10
13
9
17
5
14
5
5
16
8
8
10
6
3
7
8
8
6
5
3
5
3
3
3
2
3
3
4
6
4
4
3
7
4
4
2
3
6
3
4
0
0
2
4
2
2
4
0
3
0
1
0
2
2
2
1
1
1
0
1
1
0
5
3
3
2
0
4
2
1
2
3
4
4
1
1
2
1
0
0
0
0
0
2
0
0
1
1
2
4
3
0
3
2
0
2
3
1
2
0
1
0
2
2
0
2
0
1
1
0
1
2
1
1
1
1
0
1
2
0
4
1
2
1
2
1
4
3
2
0
0
0
2
1
1
1
1
0
0
1
1
1
3
2
1
0
4
5
1
0
0
2
1
1
2
1
0
0
1
1
0
1
0
2
2
0
1
2
1
0
0
4
0
2
3
1
1
0
0
0
2
3
0
2
0
1
2
2
0
2
0
1
0
1
0
1
3
6
0
4
1
2
1
0
2
0
0
0
0
0
1
0
5
1
0
1
0
1
0
2
4
1
1
2
1
2
1
2
3
1
1
0
2
3
0
1
0
2
4
0
1
4
0
1
1
1
0
1
2
2
1
1
2
0
0
1
1
3
1
1
0
1
1
1
0
0
0
2
0
3
1
5
2
5
3
1
6
3
3
2
5
6
6
0
2
3
2
5
6
1
3
5
0
4
3
4
1
3
2
0
2
4
3
4
0
2
0
1
2
2
0
1
3
6
1
2
1
1
1
0
2
1
0
0
1
0
3
1
2
0
0
1
3
2
2
0
0
1
1
1
5
1
1
2
1
2
0
0
1
1
1
1
1
1
0
1
0
2
2
2
1
0
2
3
0
0
2
2
5
0
0
0
3
3
3
0
2
2
2
0
0
2
5
2
2
2
5
2
1
0
1
6
2
0
2
1
4
3
2
4
11
0
10
3
2
5
2
7
8
5
16
5
7
9
7
6
3
8
6
11
10
6
5
0
10
2
5
3
4
2
0
3
1
4
0
2
1
3
2
1
1
2
1
2
1
1
4
1
2
1
2
4
1
3
0
2
2
2
2
0
1
0
5
1
0
1
2
1
3
0
3
2
1
2
1
0
0
0
0
1
0
0
2
0
2
0
3
1
0
0
3
3
1
6
3
3
0
2
1
1
2
0
2
0
0
0
2
7
2
3
0
2
3
2
0
4
4
0
0
1
1
2
3
1
1
3
1
1
3
0
3
0
1
0
3
0
0
1
1
5
0
2
1
3
0
0
0
7
0
3
2
2
2
1
0
5
5
0
0
3
3
2
1
4
2
0
2
3
1
2
4
2
3
5
3
2
9
0
1
2
0
1
2
1
1
3
1
1
2
3
4
3
0
0
0
0
3
2
6
1
2
2
2
1
1
9
4
5
3
6
7
4
0
3
1
6
2
3
1
1
2
2
2
4
2
3
3
4
1
6
5
6
3
6
4
2
5
5
2
5
4
2
4
1
3
5
4
4
4
11
6
5
4
5
2
0
7
4
4
4
6
3
2
5
3
9
4
5
3
1
5
2
9
4
1
6
6
5
4
5
5
3
6
10
3
6
4
7
8
4
16
4
9
8
2
9
7
10
6
9
11
9
7
3
6
6
8
3
9
7
10
9
9
6
6
10
10
11
16
10
10
8
12
10
14
16
20
10
7
12
11
16
7
9
7
15
14
3
9
6
8
11
8
10
12
10
16
8
15
11
17
16
15
7
18
4
9
20
14
13
10
11
13
24
10
15
7
20
17
20
18
14
12
15
18
11
19
8
23
20
13
22
23
17
13
20
23
17
27
19
24
20
29
23
26
16
36
33
27
35
40
28
42
30
41
27
25
29
36
33
31
45
50
39
41
42
55
41
46
73
59
53
60
68
80
88
73
80
112
106
111
121
102
141
161
138
157
156
225
179
186
197
270
235
230
207
297
269
298
352
350
398
389
451
465
523
524
573
587
628
642
692
690
663
716
729
741
818
749
691
672
575
582
541
470
470
334
358
295
255
251
249
235
226
241
234
244
223
278
246
316
302
286
343
293
314
340
366
354
404
405
419
421
406
471
483
509
522
564
562
552
559
551
599
635
619
668
620
693
620
688
724
684
675
793
833
765
758
795
749
798
821
829
769
709
715
635
700
583
534
513
416
398
322
321
248
192
120
125
93
57
49
40
23
23
13
15
8
7
5
4
3
10
2
6
0
4
1
0
3
2
1
0
0
1
0
0
3
1
0
0
0
1
1
0
0
1
0
1
0
0
1
0
0
0
0
0
0
1
1
1
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
</ulong>
</sequence>
<sequence name="scaling_factors" length="0" type_id="IDL:specs.de/SurfaceAnalysis/DoubleSeq:1.0" type_name="DoubleSeq">
<double/>
</sequence>
</struct>
</sequence>
<sequence name="y_curves" length="0" type_id="IDL:specs.de/Serializer/YCurveSeq:1.0" type_name="YCurveSeq">
<struct type_id="IDL:specs.de/Serializer/YCurve:1.0" type_name="YCurve">
<string name="name"/>
<double name="start"/>
<double name="delta"/>
<ulong name="curves"/>
<sequence name="data" length="0" type_id="IDL:specs.de/SurfaceAnalysis/DoubleSeq:1.0" type_name="DoubleSeq">
<double/>
</sequence>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name"/>
<any name="value"/>
</struct>
</sequence>
</struct>
</sequence>
<sequence name="xy_curves" length="0" type_id="IDL:specs.de/Serializer/XYCurveSeq:1.0" type_name="XYCurveSeq">
<struct type_id="IDL:specs.de/Serializer/XYCurve:1.0" type_name="XYCurve">
<string name="name"/>
<ulong name="curves"/>
<sequence name="data" length="0" type_id="IDL:specs.de/Serializer/PointSeq:1.0" type_name="PointSeq">
<struct type_id="IDL:specs.de/Serializer/Point:1.0" type_name="Point">
<double name="x"/>
<double name="y"/>
</struct>
</sequence>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name"/>
<any name="value"/>
</struct>
</sequence>
</struct>
</sequence>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name"/>
<any name="value"/>
</struct>
</sequence>
</struct>
</sequence>
<sequence name="compact_cycles" length="0" type_id="IDL:specs.de/Serializer/CompactCycleSeq:1.0" type_name="CompactCycleSeq">
<struct type_id="IDL:specs.de/Serializer/CompactCycle:1.0" type_name="CompactCycle">
<ulong name="time"/>
<ulong name="num_scans"/>
<sequence name="counts" length="0" type_id="IDL:specs.de/SurfaceAnalysis/DoubleSeq:1.0" type_name="DoubleSeq">
<double/>
</sequence>
<sequence name="scaled_counts" length="0" type_id="IDL:specs.de/SurfaceAnalysis/DoubleSeq:1.0" type_name="DoubleSeq">
<double/>
</sequence>
<sequence name="y_curves" length="0" type_id="IDL:specs.de/Serializer/YCurveSeq:1.0" type_name="YCurveSeq">
<struct type_id="IDL:specs.de/Serializer/YCurve:1.0" type_name="YCurve">
<string name="name"/>
<double name="start"/>
<double name="delta"/>
<ulong name="curves"/>
<sequence name="data" length="0" type_id="IDL:specs.de/SurfaceAnalysis/DoubleSeq:1.0" type_name="DoubleSeq">
<double/>
</sequence>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name"/>
<any name="value"/>
</struct>
</sequence>
</struct>
</sequence>
<sequence name="xy_curves" length="0" type_id="IDL:specs.de/Serializer/XYCurveSeq:1.0" type_name="XYCurveSeq">
<struct type_id="IDL:specs.de/Serializer/XYCurve:1.0" type_name="XYCurve">
<string name="name"/>
<ulong name="curves"/>
<sequence name="data" length="0" type_id="IDL:specs.de/Serializer/PointSeq:1.0" type_name="PointSeq">
<struct type_id="IDL:specs.de/Serializer/Point:1.0" type_name="Point">
<double name="x"/>
<double name="y"/>
</struct>
</sequence>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name"/>
<any name="value"/>
</struct>
</sequence>
</struct>
</sequence>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name"/>
<any name="value"/>
</struct>
</sequence>
</struct>
</sequence>
<sequence name="transmission" length="1094" type_id="IDL:specs.de/SurfaceAnalysis/DoubleSeq:1.0" type_name="DoubleSeq">
<double>
1263.2535771799
1864.80289964652
2466.35222211315
3067.90154457977
3669.45086704639
4271.00018951301
4872.54951197963
5474.09883444625
6075.64815691287
6677.19747937949
7278.74680184611
7880.29612431273
8481.84544677936
9083.39476924598
9684.9440917126
10286.4934141792
10888.0427366458
11489.5920591125
12091.1413815791
12692.6907040457
13294.2400265123
13895.7893489789
14497.3386714456
15098.8879939122
15700.4373163788
16301.9866388454
16903.5359613121
17505.0852837787
18106.6346062453
18708.1839287119
19309.7332511785
19911.2825736452
20512.8318961118
21114.3812185784
21715.930541045
22317.4798635116
22919.0291859783
23520.5785084449
24122.1278309115
24723.6771533781
25325.2264758447
25926.7757983114
26528.325120778
27129.8744432446
27731.4237657112
28332.9730881778
28934.5224106445
29536.0717331111
30137.6210555777
30739.1703780443
31340.719700511
31942.2690229776
32543.8183454442
33145.3676679108
33746.9169903774
34348.4663128441
34950.0156353107
35551.5649577773
36153.1142802439
36754.6636027105
37356.2129251772
37957.7622476438
38559.3115701104
39160.860892577
39762.4102150436
40363.9595375103
40965.5088599769
41567.0581824435
42168.6075049101
42770.1568273768
43371.7061498434
43973.25547231
44574.8047947766
45176.3541172432
45777.9034397099
46379.4527621765
46981.0020846431
47582.5514071097
48184.1007295763
48785.650052043
49387.1993745096
49988.7486969762
50590.2980194428
51191.8473419094
51793.3966643761
52394.9459868427
52996.4953093093
53598.0446317759
54199.5939542425
54801.1432767092
55402.6925991758
56004.2419216424
56605.791244109
57207.3405665757
57808.8898890423
58410.4392115089
59011.9885339755
59613.5378564421
60215.0871789088
60816.6365013754
61418.185823842
62019.7351463086
62621.2844687752
63222.8337912419
63824.3831137085
64425.9324361751
65027.4817586417
65629.0310811083
66230.580403575
66832.1297260416
67433.6790485082
68035.2283709748
68636.7776934414
69238.3270159081
69839.8763383747
70441.4256608413
71042.9749833079
71644.5243057746
72246.0736282412
72847.6229507078
73449.1722731744
74050.721595641
74652.2709181077
75253.8202405743
75855.3695630409
76456.9188855075
77058.4682079741
77660.0175304408
78261.5668529074
78863.116175374
79464.6654978406
80066.2148203073
80667.7641427739
81269.3134652405
81870.8627877071
82472.4121101737
83073.9614326404
83675.510755107
84277.0600775736
84878.6094000402
85480.1587225068
86081.7080449734
86683.2573674401
87284.8066899067
87886.3560123733
88487.9053348399
89089.4546573066
89691.0039797732
90292.5533022398
90894.1026247064
91495.6519471731
92097.2012696397
92698.7505921063
93300.2999145729
93901.8492370395
94503.3985595062
95104.9478819728
95706.4972044394
96308.046526906
96909.5958493726
97511.1451718392
98112.6944943059
98714.2438167725
99315.7931392391
99917.3424617057
100518.891784172
101120.441106639
101721.990429106
102323.539751572
102925.089074039
103526.638396505
104128.187718972
104729.737041439
105331.286363905
105932.835686372
106534.385008839
107135.934331305
107737.483653772
108339.032976238
108940.582298705
109542.131621172
110143.680943638
110745.230266105
111346.779588572
111948.328911038
112549.878233505
113151.427555971
113752.976878438
114354.526200905
114956.075523371
115557.624845838
116159.174168305
116760.723490771
117362.272813238
117963.822135704
118565.371458171
119166.920780638
119768.470103104
120370.019425571
120971.568748037
121573.118070504
122174.667392971
122776.216715437
123377.766037904
123979.315360371
124580.864682837
125182.414005304
125783.96332777
126385.512650237
126987.061972704
127588.61129517
128190.160617637
128791.709940104
129393.25926257
129994.808585037
130596.357907503
131197.90722997
131799.456552437
132401.005874903
133002.55519737
133604.104519837
134205.653842303
134807.20316477
135408.752487236
136010.301809703
136611.85113217
137213.400454636
137814.949777103
138416.499099569
139018.048422036
139619.597744503
140221.147066969
140822.696389436
141424.245711903
142025.795034369
142627.344356836
143228.893679302
143830.443001769
144431.992324236
145033.541646702
145635.090969169
146236.640291636
146838.189614102
147439.738936569
148041.288259035
148642.837581502
149244.386903969
149845.936226435
150447.485548902
151049.034871369
151650.584193835
152252.133516302
152853.682838768
153455.232161235
154056.781483702
154658.330806168
155259.880128635
155861.429451101
156462.978773568
157064.528096035
157666.077418501
158267.626740968
158869.176063435
159470.725385901
160072.274708368
160673.824030834
161275.373353301
161876.922675768
162478.471998234
163080.021320701
163681.570643168
164283.119965634
164884.669288101
165486.218610567
166087.767933034
166689.317255501
167290.866577967
167892.415900434
168493.965222901
169095.514545367
169697.063867834
170298.6131903
170900.162512767
171501.711835234
172103.2611577
172704.810480167
173306.359802634
173907.9091251
174509.458447567
175111.007770033
175712.5570925
176314.106414967
176915.655737433
177517.2050599
178118.754382366
178720.303704833
179321.8530273
179923.402349766
180524.951672233
181126.5009947
181728.050317166
182329.599639633
182931.148962099
183532.698284566
184134.247607033
184735.796929499
185337.346251966
185938.895574433
186540.444896899
187141.994219366
187743.543541832
188345.092864299
188946.642186766
189548.191509232
190149.740831699
190751.290154166
191352.839476632
191954.388799099
192555.938121565
193157.487444032
193759.036766499
194360.586088965
194962.135411432
195563.684733899
196165.234056365
196766.783378832
197368.332701298
197969.882023765
198571.431346232
199172.980668698
199774.529991165
200376.079313631
200977.628636098
201579.177958565
202180.727281031
202782.276603498
203383.825925965
203985.375248431
204586.924570898
205188.473893364
205790.023215831
206391.572538298
206993.121860764
207594.671183231
208196.220505698
208797.769828164
209399.319150631
210000.868473097
210602.417795564
211203.967118031
211805.516440497
212407.065762964
213008.615085431
213610.164407897
214211.713730364
214813.26305283
215414.812375297
216016.361697764
216617.91102023
217219.460342697
217821.009665163
218422.55898763
219024.108310097
219625.657632563
220227.20695503
220828.756277497
221430.305599963
222031.85492243
222633.404244896
223234.953567363
223836.50288983
224438.052212296
225039.601534763
225641.15085723
226242.700179696
226844.249502163
227445.798824629
228047.348147096
228648.897469563
229250.446792029
229851.996114496
230453.545436963
231055.094759429
231656.644081896
232258.193404362
232859.742726829
233461.292049296
234062.841371762
234664.390694229
235265.940016695
235867.489339162
236469.038661629
237070.587984095
237672.137306562
238273.686629029
238875.235951495
239476.785273962
240078.334596428
240679.883918895
241281.433241362
241882.982563828
242484.531886295
243086.081208762
243687.630531228
244289.179853695
244890.729176161
245492.278498628
246093.827821095
246695.377143561
247296.926466028
247898.475788495
248500.025110961
249101.574433428
249703.123755894
250304.673078361
250906.222400828
251507.771723294
252109.321045761
252710.870368228
253312.419690694
253913.969013161
254515.518335627
255117.067658094
255718.616980561
256320.166303027
256921.715625494
257523.26494796
258124.814270427
258726.363592894
259327.91291536
259929.462237827
260531.011560294
261132.56088276
261734.110205227
262335.659527693
262937.20885016
263538.758172627
264140.307495093
264741.85681756
265343.406140027
265944.955462493
266546.50478496
267148.054107426
267749.603429893
268351.15275236
268952.702074826
269554.251397293
270155.80071976
270757.350042226
271358.899364693
271960.448687159
272561.998009626
273163.547332093
273765.096654559
274366.645977026
274968.195299492
275569.744621959
276171.293944426
276772.843266892
277374.392589359
277975.941911826
278577.491234292
279179.040556759
279780.589879225
280382.139201692
280983.688524159
281585.237846625
282186.787169092
282788.336491559
283389.885814025
283991.435136492
284592.984458958
285194.533781425
285796.083103892
286397.632426358
286999.181748825
287600.731071291
288202.280393758
288803.829716225
289405.379038691
290006.928361158
290608.477683625
291210.027006091
291811.576328558
292413.125651024
293014.674973491
293616.224295958
294217.773618424
294819.322940891
295420.872263358
296022.421585824
296623.970908291
297225.520230757
297827.069553224
298428.618875691
299030.168198157
299631.717520624
300233.266843091
300834.816165557
301436.365488024
302037.91481049
302639.464132957
303241.013455424
303842.56277789
304444.112100357
305045.661422824
305647.21074529
306248.760067757
306850.309390223
307451.85871269
308053.408035157
308654.957357623
309256.50668009
309858.056002557
310459.605325023
311061.15464749
311662.703969956
312264.253292423
312865.80261489
313467.351937356
314068.901259823
314670.450582289
315271.999904756
315873.549227223
316475.098549689
317076.647872156
317678.197194623
318279.746517089
318881.295839556
319482.845162022
320084.394484489
320685.943806956
321287.493129422
321889.042451889
322490.591774356
323092.141096822
323693.690419289
324295.239741755
324896.789064222
325498.338386689
326099.887709155
326701.437031622
327302.986354088
327904.535676555
328506.084999022
329107.634321488
329709.183643955
330310.732966422
330912.282288888
331513.831611355
332115.380933821
332716.930256288
333318.479578755
333920.028901221
334521.578223688
335123.127546155
335724.676868621
336326.226191088
336927.775513554
337529.324836021
338130.874158488
338732.423480954
339333.972803421
339935.522125888
340537.071448354
341138.620770821
341740.170093287
342341.719415754
342943.268738221
343544.818060687
344146.367383154
344747.91670562
345349.466028087
345951.015350554
346552.56467302
347154.113995487
347755.663317954
348357.21264042
348958.761962887
349560.311285354
350161.86060782
350763.409930287
351364.959252753
351966.50857522
352568.057897687
353169.607220153
353771.15654262
354372.705865086
354974.255187553
355575.80451002
356177.353832486
356778.903154953
357380.45247742
357982.001799886
358583.551122353
359185.100444819
359786.649767286
360388.199089753
360989.748412219
361591.297734686
362192.847057153
362794.396379619
363395.945702086
363997.495024552
364599.044347019
365200.593669486
365802.142991952
366403.692314419
367005.241636886
367606.790959352
368208.340281819
368809.889604285
369411.438926752
370012.988249219
370614.537571685
371216.086894152
371817.636216618
372419.185539085
373020.734861552
373622.284184018
374223.833506485
374825.382828952
375426.932151418
376028.481473885
376630.030796351
377231.580118818
377833.129441285
378434.678763751
379036.228086218
379637.777408685
380239.326731151
380840.876053618
381442.425376084
382043.974698551
382645.524021018
383247.073343484
383848.622665951
384450.171988417
385051.721310884
385653.270633351
386254.819955817
386856.369278284
387457.918600751
388059.467923217
388661.017245684
389262.56656815
389864.115890617
390465.665213084
391067.21453555
391668.763858017
392270.313180484
392871.86250295
393473.411825417
394074.961147883
394676.51047035
395278.059792817
395879.609115283
396481.15843775
397082.707760216
397684.257082683
398285.80640515
398887.355727616
399488.905050083
400090.45437255
400692.003695016
401293.553017483
401895.10233995
402496.651662416
403098.200984883
403699.750307349
404301.299629816
404902.848952283
405504.398274749
406105.947597216
406707.496919682
407309.046242149
407910.595564616
408512.144887082
409113.694209549
409715.243532016
410316.792854482
410918.342176949
411519.891499415
412121.440821882
412722.990144349
413324.539466815
413926.088789282
414527.638111749
415129.187434215
415730.736756682
416332.286079148
416933.835401615
417535.384724082
418136.934046548
418738.483369015
419340.032691482
419941.582013948
420543.131336415
421144.680658881
421746.229981348
422347.779303815
422949.328626281
423550.877948748
424152.427271214
424753.976593681
425355.525916148
425957.075238614
426558.624561081
427160.173883548
427761.723206014
428363.272528481
428964.821850947
429566.371173414
430167.920495881
430769.469818347
431371.019140814
431972.568463281
432574.117785747
433175.667108214
433777.21643068
434378.765753147
434980.315075614
435581.86439808
436183.413720547
436784.963043013
437386.51236548
437988.061687947
438589.611010413
439191.16033288
439792.709655347
440394.258977813
440995.80830028
441597.357622746
442198.906945213
442800.45626768
443402.005590146
444003.554912613
444605.10423508
445206.653557546
445808.202880013
446409.752202479
447011.301524946
447612.850847413
448214.400169879
448815.949492346
449417.498814813
450019.048137279
450620.597459746
451222.146782212
451823.696104679
452425.245427146
453026.794749612
453628.344072079
454229.893394546
454831.442717012
455432.992039479
456034.541361945
456636.090684412
457237.640006879
457839.189329345
458440.738651812
459042.287974279
459643.837296745
460245.386619212
460846.935941678
461448.485264145
462050.034586612
462651.583909078
463253.133231545